openapi: 3.0.0
info:
  title: Counterparty API
  description: API для управления контрагентами и аутентификации пользователей
  version: 1.0.0
servers:
  - url: http://localhost:8000/api
    description: Локальный сервер
paths:
  /register:
    post:
      tags:
        - Auth
      summary: Регистрация нового пользователя
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                  example: user@example.com
                password:
                  type: string
                  format: password
                  example: password
      responses:
        '200':
          description: Пользователь успешно зарегистрирован
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1
                  email:
                    type: string
                    example: user@example.com
        '422':
          description: Ошибка валидации
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: The given data was invalid.
                  errors:
                    type: object
                    example:
                      email: ["The email field is required."]
                      password: ["The password field is required."]
  /login:
    post:
      tags:
        - Auth
      summary: Аутентификация пользователя
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                  example: user@example.com
                password:
                  type: string
                  format: password
                  example: password
      responses:
        '200':
          description: Успешная аутентификация
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 1
                      email:
                        type: string
                        example: user@example.com
                  token:
                    type: string
                    example: "1|abcdef1234567890"
        '401':
          description: Неверные учетные данные
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Invalid credentials.
  /counterparties:
    post:
      tags:
        - Counterparties
      summary: Создание нового контрагента
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - inn
              properties:
                inn:
                  type: string
                  example: "7707083893"
      responses:
        '201':
          description: Контрагент успешно создан
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1
                  name:
                    type: string
                    example: "ПАО СБЕРБАНК"
                  inn:
                    type: string
                    example: "7707083893"
                  ogrn:
                    type: string
                    example: "1027700132195"
                  address:
                    type: string
                    example: "117312, г Москва, ул Вавилова, д 19"
                  user_id:
                    type: integer
                    example: 1
        '401':
          description: Неавторизованный доступ
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
        '422':
          description: Ошибка валидации
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: The given data was invalid.
                  errors:
                    type: object
                    example:
                      inn: ["The inn field is required."]
    get:
      tags:
        - Counterparties
      summary: Получение списка контрагентов
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Список контрагентов успешно получен
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1
                  email:
                    type: string
                    example: user@example.com
                  counterparties:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 1
                        name:
                          type: string
                          example: "ПАО СБЕРБАНК"
                        inn:
                          type: string
                          example: "7707083893"
                        ogrn:
                          type: string
                          example: "1027700132195"
                        address:
                          type: string
                          example: "117312, г Москва, ул Вавилова, д 19"
        '401':
          description: Неавторизованный доступ
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT